FROM node:20-alpine

RUN apk add --no-cache aws-cli

WORKDIR /app

COPY package*.json ./

RUN npm ci --only=production

COPY . .

RUN mkdir -p /app/DATAROOT /app/LOG /app/ASSETS && \
    chmod +x /app/osc-entrypoint.sh

ENTRYPOINT ["/app/osc-entrypoint.sh"]
